authnapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

import authnapp.views as authnapp
from authnapp.apps import AuthnappConfig
from authnapp.views import ProfileView, ProfilePublishedArticlesView, \
    ImageListView, PictureFileCreateView, PictureFileDeleteView, \
    PictureFileUpdateView, MyCommentsListView, ToMeCommentsListView, \
    SearchImageView, ProfileDraftsArticlesView, ProfileDeniedArticlesView, \
    ProfileOnModerationArticlesView, MyMessagesListView, \
    ProfileArticleToModerationView, MessageIsReadView
from .api import HabrUserApi

arouter = DefaultRouter()
arouter.register('habrusers', HabrUserApi)

app_name = AuthnappConfig.name

urlpatterns = [
    path("login/", authnapp.login, name="login"),
    path("logout/", authnapp.logout, name="logout"),
    path("register/", authnapp.register, name="register"),
    path("edit/", authnapp.edit, name="edit"),
    path("password_reset/", authnapp.MyPasswordResetView.as_view(), name='password_reset'),
    path("password_reset_done/", authnapp.MyPasswordResetDone.as_view(), name='password_reset_done'),
    path("reset/<uidb64>/<token>/", authnapp.MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path("password_reset_complete/", authnapp.MyPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('profile/<uuid:pk>/', ProfileView.as_view(), name='profile'),
    path('published_articles/<uuid:pk>/', ProfilePublishedArticlesView.as_view(), name='published_user_articles'),
    path('draft_articles/<uuid:pk>/', ProfileDraftsArticlesView.as_view(), name='draft_user_articles'),
    path('denied_articles/<uuid:pk>/', ProfileDeniedArticlesView.as_view(), name='denied_user_articles'),
    path('on_moderation_articles/<uuid:pk>/', ProfileOnModerationArticlesView.as_view(), name='on_moderation_user_articles'),
    path('article_to_moderation/<slug:article_slug>/', ProfileArticleToModerationView.as_view(),
         name='article_to_moderation'),

    path('api/', include(arouter.urls)),

    path('images/<uuid:pk>/', ImageListView.as_view(), name='user_images'),
    path('load_images/<uuid:pk>/', PictureFileCreateView.as_view(), name='load_images'),
    path('delete_images/<slug:picture_slug>/', PictureFileDeleteView.as_view(),
         name='delete_images'),
    path('update_images/<slug:picture_slug>/', PictureFileUpdateView.as_view(),
         name='update_images'),
    path('search_images/<uuid:pk>/', SearchImageView.as_view(), name='search_images'),

    path('my_comments/<uuid:pk>/', MyCommentsListView.as_view(), name='user_comments'),
    path('to_me_comments/<uuid:pk>/', ToMeCommentsListView.as_view(), name='to_me_comments'),

    path('my_messages/<uuid:pk>/', MyMessagesListView.as_view(), name='user_messages'),
    path('read_message/<slug:slug>/', MessageIsReadView.as_view(), name='read_message'),
]

habr/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework.permissions import AllowAny

from articles.views import MainView, SearchView, page_not_found_view, create_article, help_view, update_article, \
    ArticleCommentRatingView, ArticleLikeRatingView, UserRatingView

schema_view = get_schema_view(
    openapi.Info(
        title="Habr",
        default_version='0.1',
        description="Documentation to out project",
        contact=openapi.Contact(email="admin@admin.local"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=[AllowAny],
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", MainView.as_view(), name="index"),
    path("articles/", include("articles.urls", namespace="articles")),
    path("auth/", include("authnapp.urls", namespace="auth")),
    path('moderation/', include('moderation.urls', namespace='moderation')),
    path("", include("social_django.urls", namespace="social")),
    path('create_article/', create_article, name='create_article'),
    path('update_article/<slug:article_slug>/', update_article, name='update_article'),
    path('search/', SearchView.as_view(), name='search_view'),
    path('search/like/<str:search_string>/', SearchView.as_view(), name='search_view_sort_like'),
    path('search/new/<str:search_string>/', SearchView.as_view(), name='search_view_sort_new'),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('help/', help_view, name='help'),
    path('404/', page_not_found_view,
         kwargs={'exception': Exception('Page not Found')}, name='page_404'),
    path('martor/', include('martor.urls')),
    path("best_articles/", ArticleLikeRatingView.as_view(), name="best_articles"),
    path("discussed_articles/", ArticleCommentRatingView.as_view(), name="discussed_articles"),
    path("users_rating/", UserRatingView.as_view(), name="users_rating"),
]

handler404 = "habr.views.page_not_found_view"

urlpatterns += [re_path('^__debug_/', include(debug_toolbar.urls))]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('404/', page_not_found_view,
                         kwargs={'exception': Exception('Page not Found')}, name='page_404')]

authnapp/views.py
import logging

from django.conf import settings
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, \
    PasswordResetCompleteView, reverse_lazy
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
from django.db import transaction
from django.db.models import Q, Count
from django.shortcuts import HttpResponseRedirect, render, redirect
from django.urls import reverse
from django.utils.datastructures import MultiValueDictKeyError
from django.utils.timezone import now
from django.views import View
from django.views.generic import ListView, DetailView, TemplateView, DeleteView, UpdateView

from articles.models import Article, PictureFile, Comment, Message
from articles.views import ArticleLikeRatingView
from authnapp.forms import (HabrUserEditForm, HabrUserLoginForm,
                            HabrUserProfileEditForm, HabrUserRegisterForm, ImageFormSet, ImageUpdatePicturesForm)
from authnapp.models import HabrUser, HabrUserProfile
from habr.mixin import AuthorizedOnlyDispatchMixin
from habr.settings import DOMAIN_NAME

logger = logging.getLogger(__name__)


def login(request):
    title = "Вход в систему"

    login_form = HabrUserLoginForm(data=request.POST or None)

    if request.method == "POST" and login_form.is_valid():
        username = request.POST["username"]
        password = request.POST["password"]
        key = 'next'

        try:
            next_page = request.GET[key]
        except MultiValueDictKeyError:
            logger.error('There is no key %s in the request.GET dictionary that should point to the page '
                         'to which the user will return after authentication. '
                         'The user %s was redirected to the main page.'
                         , key, request.user.username)
            next_page = '/'

        user = auth.authenticate(username=username, password=password)
        if user and user.banned_until and user.banned_until < now():
            user.banned_until = None
            user.save()
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(next_page)

    context = {"title": title, "login_form": login_form}
    return render(request, "authnapp/authentification/login.html", context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    title = "Регистрация"

    if request.method == "POST":
        register_form = HabrUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            from articles.models import Message, MessageType
            user = HabrUser.objects.get(username=register_form.cleaned_data['username'])
            try:
                message_sys_type = MessageType.objects.get(sys_type='HELLO')

                Message.objects.create(message_type=message_sys_type,
                                       user=user,
                                       text=f'Добро пожаловать на {DOMAIN_NAME}, дорогой наш '
                                            f'{user.first_name} {user.last_name}!')
            except ObjectDoesNotExist:
                pass
            return HttpResponseRedirect(reverse("auth:login"))
    else:
        register_form = HabrUserRegisterForm()

    context = {"title": title, "register_form": register_form}
    return render(request, "authnapp/authentification/register.html", context)


@login_required
@transaction.atomic
def edit(request):
    title = "Редактирование"

    if request.method == "POST":
        edit_form = HabrUserEditForm(request.POST, request.FILES, instance=request.user)
        profile_form = HabrUserProfileEditForm(request.POST, instance=request.user.habruserprofile)
        if edit_form.is_valid() and profile_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:profile', args=[request.user.habruserprofile.uuid]))
        return HttpResponseRedirect(reverse("auth:edit"))
    else:
        edit_form = HabrUserEditForm(instance=request.user)
        profile_form = HabrUserProfileEditForm(instance=request.user.habruserprofile)

    context = {"title": title, "edit_form": edit_form, "profile_form": profile_form, "media_url": settings.MEDIA_URL}

    return render(request, "authnapp/profile/edit.html", context)


def send_verify_mail(user):
    verify_link = reverse("auth:verify", args=[user.email, user.activation_key])

    title = f"Подтверждение учетной записи {user.username}"
    message = f"Для подтверждения учетной записи {user.username} " \
              f"на портале {settings.DOMAIN_NAME} перейдите по ссылке: \
    \n{settings.DOMAIN_NAME}{verify_link}"

    print(f"from: {settings.EMAIL_HOST_USER}, to: {user.email}")
    return send_mail(
        title,
        message,
        settings.EMAIL_HOST_USER,
        [user.email],
        fail_silently=False,
    )


def verify(request, email, activation_key):
    try:
        user = HabrUser.objects.get(email=email)
        if user.activation_key == activation_key and not user.is_activation_key_expired():
            logger.info("User %s is activated.", user)
            user.is_active = True
            user.save()
            auth.login(request, user, backend="django.contrib.auth.backends.ModelBackend")

            return render(request, "authnapp/authentification/verification.html")
        logger.error("Error activation user: %s.", user)
        return render(request, "authnapp/authentification/verification.html")

    except Exception as e:
        logger.error("Error activation user : %s.", e.args)

    return HttpResponseRedirect(reverse("index"))


class MyPasswordResetView(PasswordResetView):
    email_template_name = 'authnapp/authentification/password_reset_email.html'

    success_url = reverse_lazy('auth:password_reset_done')

    template_name = 'authnapp/authentification/password_reset.html'


class MyPasswordResetDone(PasswordResetDoneView):
    template_name = 'authnapp/authentification/password_reset_done.html'
    title = 'Запрос на сброс пароля отправлен'


class MyPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'authnapp/authentification/password_reset_confirm.html'
    success_url = reverse_lazy('auth:password_reset_complete')


class MyPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'authnapp/authentification/password_reset_complete.html'
    title = 'Сброс пароля завершен'


class ProfileView(DetailView, AuthorizedOnlyDispatchMixin):
    """A view for the users to view their profile."""
    model = HabrUserProfile
    template_name = 'authnapp/includes/profile_data.html'

    def get_context_data(self, **kwargs):
        """Adds the page title to the context and returns it."""
        context = super().get_context_data(**kwargs)
        context['user'] = context['habruserprofile'].user
        context['title'] = f'Профиль пользователя {context["user"].username}'
        return context


class ProfileBaseArticleView(ListView, AuthorizedOnlyDispatchMixin):
    """A base view for viewing a list of articles written by the user.

    Parameters:
        * flag(str): the default value is 'DRAFT'. Switching the parameter
                         allows you to return a queryset of articles with different
                         status:
                         'DRAFT' - drafts only, not published;
                         'DENY' - rejected by the moderator, not published;
                         'ACTIVE' - approved by the moderator, published;
    """
    model = HabrUser
    template_name = 'authnapp/includes/articles_data.html'
    context_object_name = 'user_articles'
    paginate_by = 3
    flag = 'DRAFT'

    def get_queryset(self):
        """Returns a queryset of articles of the specified user.
        The type of articles determines the flag.
        """
        current_user = self.request.user
        return Article.objects.filter(Q(user=current_user), Q(is_active=self.flag))

    def get_context_data(self, **kwargs):
        """Adds the current user and the type of articles to the context and returns it."""
        context = super().get_context_data(**kwargs)
        context['habruserprofile'] = HabrUserProfile.objects.get(user=self.request.user)
        context['flag'] = self.flag
        return context


class ProfilePublishedArticlesView(ProfileBaseArticleView):
    """A view for viewing a list of active articles written by the user."""
    flag = 'ACTIVE'

    def get_context_data(self, **kwargs):
        """Adds the page title to the context and returns it."""
        context = super().get_context_data(**kwargs)
        context['title'] = f'Опубликованные статьи {self.request.user.username}'
        return context


class ProfileDraftsArticlesView(ProfileBaseArticleView):
    """A view for viewing a list of draft articles written by the user."""

    def get_context_data(self, **kwargs):
        """Adds the page title to the context and returns it."""
        context = super().get_context_data(**kwargs)
        context['title'] = f'Черновики {self.request.user.username}'
        return context


class ProfileDeniedArticlesView(ProfileBaseArticleView):
    """A view for viewing a list of denied articles written by the user."""
    flag = 'DENY'

    def get_context_data(self, **kwargs):
        """Adds the page title to the context and returns it."""
        context = super().get_context_data(**kwargs)
        context['title'] = f'Отклоненные статьи {self.request.user.username}'
        return context


class ProfileOnModerationArticlesView(ProfileBaseArticleView):
    """A view for viewing a list of articles submitted for moderation written by the user."""
    flag = 'MODER'

    def get_context_data(self, **kwargs):

authnapp/templates/authnapp/profile/profile-search-images.html
{% extends 'articles/base.html' %}
{#{% extends 'authnapp/profile/profile.html' %}#}
{% load static %}


{% block content %}
    {% include 'authnapp/includes/image_modal.html' %}
    <div id="layoutSidenav_content">
        <main>

            <div class="container-fluid text-center menu-font">
                <h1 class="mt-4">
                    {% block title %}{{ title }}{% endblock %}
                </h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <div class="row justify-content-center">
                            <div class="col-6">
                                <a class="btn btn-primary btn-grey btn-block mb-4"
                                   href="{% url 'auth:user_images' habruserprofile.uuid %}">
                                    Перейти в Мои картинки
                                </a>
                            </div>
                        </div>

                        <div id="infinite-container" class="infinite-container">
                            <div class="infinite-item row justify-content-center">

                                {% for image in search_pictures %}

                                    <div class="col-4">
                                        <div class="row border border-grey btn-light m-1">
                                            <div class="thumbnail col-12" id="{{ image.slug }}">
                                                <img class="thumbnail img-fluid img-rounded img-responsive img-thumbnail m-2 border border-grey"
                                                     width="50%"
                                                     src=" {{ image.image_url }}"
                                                     alt="">
                                            </div>
                                            <div class="col-12 placeholders-text">
                                                <p>{{ image.create_time }}</p>
                                                <p class="border border-grey">{{ image.file_name }}</p>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>

                        <div class="card-footer">
                            <!-- Старое меню пагинации -->
                            <nav aria-label="Page navigation">
                                <ul class="pagination justify-content-center">
                                    <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                                        <a class="page-link menu-font btn btn-sm btn-outline-dark rounded-3
                                                        {% if page_obj.has_previous %} btn-grey dark-grey {% else %} btn-grey-disabled {% endif %}"
                                           href="{% if page_obj.has_previous %} ?page={{ page_obj.previous_page_number }}
                                                        {% else %} # {% endif %}"
                                           tabindex="-1" aria-disabled="true"><i class="fas fa-backward"></i></a>
                                    </li>
                                    {% for page in page_obj.paginator.page_range %}
                                        <li class="page-item">
                                            <a class="page-link menu-font btn btn-sm btn-outline-dark rounded-3 btn-grey dark-grey"
                                               href="?page={{ page }}">{{ page }}</a>
                                        </li>
                                    {% endfor %}
                                    <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                                        <a class="page-link menu-font btn btn-sm btn-outline-dark rounded-3
                                                        {% if page_obj.has_next %} btn-grey dark-grey {% else %} btn-grey-disabled {% endif %}"
                                           href="{% if page_obj.has_next %} ?page={{ page_obj.next_page_number }}
                                                           {% else %} # {% endif %}"><i class="fas fa-forward"></i></a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
{% endblock %}

authnapp/templates/authnapp/profile/profile-update-pictures.html
{% extends 'articles/base.html' %}
{% load static %}


{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <form id="image-forms" action="{% url 'auth:update_images' object.slug %}" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <div class="container-fluid text-center">
                    <h3 class="mt-4">{% block title %}{{ title }}{% endblock %}</h3>

                    <!-- Здесь можно размещать сообщения для пользователя (ошибки, уведомления) -->
                    {% if messages %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {% for message in messages %}
                                <div{% if message.tags %}
                                    class="{{ message.tags }}"{% endif %}>{{ message|escape }}</div>
                            {% endfor %}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}

                    {% if form.non_field_errors %}
                        <li>{{ form.non_field_errors }}</li>
                    {% endif %}
                    {% for field in form %}
                        {% if field.errors %}
                            <div class="card-body border border-grey text-left">
                                <div><i class="fa fa-warning"></i> Ошибки заполнения формы:</div>
                                {{ field.errors }}
                            </div>
                        {% endif %}
                    {% endfor %}

                    <div id="form-container" class="row justify-content-center">

                        <!-- Форма изменения картинки -->
                        <div class="col-6 image-form">
                            <div class="shadow-lg border-0 rounded-lg m-3">
                                <div class="header-h2">
                                    <div class="col-12">
                                        <div class="form-group">
                                            <label class="small mb-1"
                                                   for="{{ form.file_name.id_for_label }}">Заголовок
                                                картинки</label>
                                            {{ form.file_name }}
                                        </div>
                                    </div>
                                </div>
                                <div class="justify-content-center">
                                    <div class="form-row mb-4">

                                        <div class="col-12 mb-4">
                                            <img src="{% if picturefile.picture_file %} {{ picturefile.picture_file.url }} {% else %} {% static 'vendor/img/no_image.png' %} {% endif %}"
                                                 height="300vh" alt="">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <button class="btn btn-grey btn-outline-info btn-block" type="submit">Отредактировать</button>
                        <button class="btn btn-outline-secondary btn-block" type="button"
                                onClick="javascript:history.go(-1);">Отмена
                        </button>
                    </div>
                </div>

            </form>
        </main>
        {% include 'articles/includes/footer.html' %}
    </div>
{% endblock %}

authnapp/templates/authnapp/profile/profile.html
{% extends 'articles/base.html' %}
{% load static %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>

            <!-- Вывод сообщений формы-->
            <div>
                <ul class="errorlist">
                    {% if messages %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {% for message in messages %}
                                <div{% if message.tags %}
                                    class="{{ message.tags }} mt-2"{% endif %}>{{ message|escape }}</div>
                            {% endfor %}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                </ul>
            </div>

            <div class="container-fluid text-center">
                <h1 class="mt-4">
                    {% block title %}{{ title }}{% endblock %}
                </h1>
                <div class="row row-cols-5 justify-content-center mt-4">
                    <div class="col">
                        <a class="btn btn-block btn-primary"
                           href="{% url 'auth:profile' habruserprofile.uuid %}">
                            <span class="small-text">Обо мне</span></a>
                    </div>
                    <div class="col">
                        <a class="btn btn-block btn-primary"
                           href='{% url 'auth:published_user_articles' habruserprofile.uuid %}'>
                            <span class="small-text">Мои статьи</span></a>
                    </div>
                    <div class="col">
                        <a class="btn btn-block btn-primary"
                           href="{% url 'auth:user_comments' habruserprofile.uuid %}"><span class="small-text">Мои комментарии</span></a>
                    </div>
                    <div class="col">
                        <a class="btn btn-block btn-primary"
                           href="{% url 'auth:user_images' habruserprofile.uuid %}">
                            <span class="small-text">Мои картинки</span></a>
                    </div>
                    <div class="col">
                        <a class="btn btn-block btn-primary"
                           href='{% url 'auth:user_messages' habruserprofile.uuid %}'>
                            <span class="small-text">Мои сообщения</span></a>
                    </div>
                </div>

                <div class="row justify-content-center text-left mt-1 mb-1 row-flex" id="profile-content">
                    {% block profile-content %}
                    {% endblock %}
                </div>
            </div>
        </main>
        {% include 'articles/includes/footer.html' %}
    </div>
{% endblock %}