articles/urls.py
from django.urls import path, include
from articles.views import ArticleView, CategoryView, TagArticleView, LikeToAuthorView, UserArticleView, CommentDeleteView, CommentLikeView
from .api import TagApi, ArticleApi, CommentApi, LikeApi, PictureFileApi, MessageApi
from rest_framework.routers import DefaultRouter


router = DefaultRouter()
router.register('tags', TagApi)
router.register('articles', ArticleApi, basename='Article')
router.register('comments', CommentApi)
router.register('likes', LikeApi)
router.register('picturefile', PictureFileApi)
router.register('message', MessageApi)

app_name = 'articles'
urlpatterns = [
    path('categories/<slug:category_slug>/', CategoryView.as_view(), name='category_read'),
    path('<slug:article_slug>/', ArticleView.as_view(), name='article_read'),
    path('tags/<slug:tag_slug>/', TagArticleView.as_view(), name='tag_articles'),
    path('like_article/<slug:slug>/', LikeToAuthorView.as_view(), name='article_like'),
    path('delete_comment/<slug:comment_id>/', CommentDeleteView.as_view(), name='comment_delete'),
    path('like_comment/<slug:comment_id>/', CommentLikeView.as_view(), name='comment_like'),
    path('user_articles/<slug:user_id>/', UserArticleView.as_view(), name='user_articles'),
    path('api/', include(router.urls)),
]

authnapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

import authnapp.views as authnapp
from authnapp.apps import AuthnappConfig
from authnapp.views import ProfileView, ProfilePublishedArticlesView, \
    ImageListView, PictureFileCreateView, PictureFileDeleteView, \
    PictureFileUpdateView, MyCommentsListView, ToMeCommentsListView, \
    SearchImageView, ProfileDraftsArticlesView, ProfileDeniedArticlesView, \
    ProfileOnModerationArticlesView, MyMessagesListView, \
    ProfileArticleToModerationView, MessageIsReadView
from .api import HabrUserApi

arouter = DefaultRouter()
arouter.register('habrusers', HabrUserApi)

app_name = AuthnappConfig.name

urlpatterns = [
    path("login/", authnapp.login, name="login"),
    path("logout/", authnapp.logout, name="logout"),
    path("register/", authnapp.register, name="register"),
    path("edit/", authnapp.edit, name="edit"),
    path("password_reset/", authnapp.MyPasswordResetView.as_view(), name='password_reset'),
    path("password_reset_done/", authnapp.MyPasswordResetDone.as_view(), name='password_reset_done'),
    path("reset/<uidb64>/<token>/", authnapp.MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path("password_reset_complete/", authnapp.MyPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('profile/<uuid:pk>/', ProfileView.as_view(), name='profile'),
    path('published_articles/<uuid:pk>/', ProfilePublishedArticlesView.as_view(), name='published_user_articles'),
    path('draft_articles/<uuid:pk>/', ProfileDraftsArticlesView.as_view(), name='draft_user_articles'),
    path('denied_articles/<uuid:pk>/', ProfileDeniedArticlesView.as_view(), name='denied_user_articles'),
    path('on_moderation_articles/<uuid:pk>/', ProfileOnModerationArticlesView.as_view(), name='on_moderation_user_articles'),
    path('article_to_moderation/<slug:article_slug>/', ProfileArticleToModerationView.as_view(),
         name='article_to_moderation'),

    path('api/', include(arouter.urls)),

    path('images/<uuid:pk>/', ImageListView.as_view(), name='user_images'),
    path('load_images/<uuid:pk>/', PictureFileCreateView.as_view(), name='load_images'),
    path('delete_images/<slug:picture_slug>/', PictureFileDeleteView.as_view(),
         name='delete_images'),
    path('update_images/<slug:picture_slug>/', PictureFileUpdateView.as_view(),
         name='update_images'),
    path('search_images/<uuid:pk>/', SearchImageView.as_view(), name='search_images'),

    path('my_comments/<uuid:pk>/', MyCommentsListView.as_view(), name='user_comments'),
    path('to_me_comments/<uuid:pk>/', ToMeCommentsListView.as_view(), name='to_me_comments'),

    path('my_messages/<uuid:pk>/', MyMessagesListView.as_view(), name='user_messages'),
    path('read_message/<slug:slug>/', MessageIsReadView.as_view(), name='read_message'),
]

habr/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework.permissions import AllowAny

from articles.views import MainView, SearchView, page_not_found_view, create_article, help_view, update_article, \
    ArticleCommentRatingView, ArticleLikeRatingView, UserRatingView

schema_view = get_schema_view(
    openapi.Info(
        title="Habr",
        default_version='0.1',
        description="Documentation to out project",
        contact=openapi.Contact(email="admin@admin.local"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=[AllowAny],
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", MainView.as_view(), name="index"),
    path("articles/", include("articles.urls", namespace="articles")),
    path("auth/", include("authnapp.urls", namespace="auth")),
    path('moderation/', include('moderation.urls', namespace='moderation')),
    path("", include("social_django.urls", namespace="social")),
    path('create_article/', create_article, name='create_article'),
    path('update_article/<slug:article_slug>/', update_article, name='update_article'),
    path('search/', SearchView.as_view(), name='search_view'),
    path('search/like/<str:search_string>/', SearchView.as_view(), name='search_view_sort_like'),
    path('search/new/<str:search_string>/', SearchView.as_view(), name='search_view_sort_new'),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('help/', help_view, name='help'),
    path('404/', page_not_found_view,
         kwargs={'exception': Exception('Page not Found')}, name='page_404'),
    path('martor/', include('martor.urls')),
    path("best_articles/", ArticleLikeRatingView.as_view(), name="best_articles"),
    path("discussed_articles/", ArticleCommentRatingView.as_view(), name="discussed_articles"),
    path("users_rating/", UserRatingView.as_view(), name="users_rating"),
]

handler404 = "habr.views.page_not_found_view"

urlpatterns += [re_path('^__debug_/', include(debug_toolbar.urls))]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('404/', page_not_found_view,
                         kwargs={'exception': Exception('Page not Found')}, name='page_404')]

moderation/urls.py
from django.urls import path

from moderation.views import ModerationPanelView, UserListView,\
    UserDetailView, UserDeleteView, UserGetsBannedView, \
    ArticlesModerListView, ArticleModerDetailView, ArticleRejectedListView, \
    ArticleRejectedDetailView, MessagesListView

app_name = 'moderation'


urlpatterns = [
    path('', ModerationPanelView.as_view(), name='moderation_index'),

    path('users/', UserListView.as_view(), name='moderation_users'),
    path('user-moderation/<uuid:pk>/', UserDetailView.as_view(), name='moderation_user_detail'),
    path('user-delete/<uuid:pk>/', UserDeleteView.as_view(), name='moderation_user_delete'),
    path('user-ban/<uuid:pk>/', UserGetsBannedView.as_view(), name='moderation_user_ban'),

    path('articles/', ArticlesModerListView.as_view(), name='moderation_articles'),
    path('article-moderation/<slug:article_slug>/', ArticleModerDetailView.as_view(),
         name='moderation_article_detail'),
    path('deny-articles/', ArticleRejectedListView.as_view(), name='deny_articles'),
    path('article-recover/<slug:article_slug>/', ArticleRejectedDetailView.as_view(),
         name='recover_article_detail'),

    path('calls/', MessagesListView.as_view(), name='moderation_calls'),
]

moderation/models.py
from django.db import models

# Create your models here.

moderation/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from authnapp.models import HabrUser


class UserBanForm(UserChangeForm):
    """Form for banning users."""
    banned_until = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])

    class Meta:
        """Defines the model involved and the fields used in the form.
        """
        model = HabrUser
        fields = ('username', 'banned_until')

    def __init__(self, *args, **kwargs):
        """Manages the class of form field 'username' for its correct display on the page.
        Sets the read-only mode for the 'username' field to prohibit its editing.
        """
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['readonly'] = True
        self.fields['username'].widget.attrs['class'] = 'form-control py-4'

moderation/templates/moderation/includes/inc_moder_auth.html
{% if request.user.is_superuser %}
    <a class="dropdown-item" href="/admin">Админка</a>
{% endif %}

{% if request.user.is_authenticated %}
    <a class="dropdown-item" href="{% url 'auth:profile' user.habruserprofile.uuid %}">Личный кабинет: {{ user.username }}</a>
    <a class="dropdown-item" href="{% url 'auth:logout' %}">Выйти из профиля</a>
{% endif %}

moderation/templates/moderation/includes/table-articles.html
<div class="table-responsive">
    <table class="table table-bordered wigth-100 dtBasicExample" id="example">
        <thead>
        <tr>
            <th>Категория</th>
            <th>Заголовок</th>
            <th>Автор</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <th>Категория</th>
            <th>Заголовок</th>
            <th>Автор</th>
        </tr>
        </tfoot>
        <tbody class="text-left">
        {% for article in page_obj %}
            <tr>
                <td>{{ article.article_category }}</td>
                <td>

                    {% if request.path == defaul_path %}
                        <a href="{% url 'moderation:moderation_article_detail' article.slug %}" class="admin-link">
                    {% else %}
                        <a href="{% url 'moderation:recover_article_detail' article.slug %}" class="admin-link">
                    {% endif %}

                    {{ article.title }}</a>
                </td>
                <td>{{ article.user }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

moderation/templates/moderation/includes/table-messages.html
<div class="table-responsive">
    <table class="table table-bordered wigth-100 dtBasicExample" id="example">
        <thead>
        <tr>
            <th>Сообщение</th>
            <th>Перейти к статье</th>
            <th>Перейти к комментарию</th>
            <th>Прочитано</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <th>Сообщение</th>
            <th>Перейти к статье</th>
            <th>Перейти к комментарию</th>
            <th>Прочитано</th>
        </tr>
        </tfoot>
        <tbody class="text-left">
        {% for message in page_obj %}
            <tr {% if message.is_read %}style="background-color: #A69888" {% endif %}>
                <td>
                    {{ message.text | safe }}
                </td>
                <td>
                    <a href="{% url 'articles:article_read' message.related_article.slug %}">
                        Переход к статье</a>
                </td>
                <td>
                    <a href="{% url 'articles:article_read' message.related_article.slug %}#{{ message.related_comment.slug }}">Перейти
                        к комментарию</a></td>
                <td><a class='btn btn-outline-dark btn-grey'
                       href='{% url 'auth:read_message' message.slug %}'>{% if message.is_read %}
                    <i class="fas fa-check">
                {% else %}<i class="fas fa-eye">{% endif %}</i>
                </a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

moderation/templates/moderation/includes/table-users.html
<div class="table-responsive">
    <table class="table table-bordered wigth-100 dtBasicExample" id="example">
        <thead>
        <tr>
            <th>Персонал</th>
            <th>Никнейм</th>
            <th>Email</th>
            <th>Возраст</th>
            <th>Карма</th>
            <th>Статус</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <th>Персонал</th>
            <th>Никнейм</th>
            <th>Email</th>
            <th>Возраст</th>
            <th>Карма</th>
            <th>Статус</th>
        </tr>
        </tfoot>
        <tbody>
        {% for user in page_obj %}
            <tr {% if not user.is_active %} class="no-active"
            {% elif user.is_staff %} class="site-staff"
            {% elif user.banned_until %} class="banned"> {% endif %}>
                <td> {% if user.is_superuser %}<i class="fa fa-crown mr-2"></i>
                {% elif user.is_staff %}<i class="fa fa-star mr-2"></i>{% endif %}</td>
                <td>
                    <a href="{% url 'moderation:moderation_user_detail' user.uuid %}"
                       class="admin-link">
                        {{ user.username }}</a>
                </td>
                <td>{{ user.email }}</td>
                <td>{{ user.age }}</td>
                <td>{{ user.likes }}</td>
                <td>
                    {% if not user.is_active %}
                         Удален
                    {% elif user.banned_until %}
                         Бан до: {{ user.banned_until | date }}
                    {% else %}Активен
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>