articles/urls.py
from django.urls import path, include
from articles.views import ArticleView, CategoryView, TagArticleView, LikeToAuthorView, UserArticleView, CommentDeleteView, CommentLikeView
from .api import TagApi, ArticleApi, CommentApi, LikeApi, PictureFileApi, MessageApi
from rest_framework.routers import DefaultRouter


router = DefaultRouter()
router.register('tags', TagApi)
router.register('articles', ArticleApi, basename='Article')
router.register('comments', CommentApi)
router.register('likes', LikeApi)
router.register('picturefile', PictureFileApi)
router.register('message', MessageApi)

app_name = 'articles'
urlpatterns = [
    path('categories/<slug:category_slug>/', CategoryView.as_view(), name='category_read'),
    path('<slug:article_slug>/', ArticleView.as_view(), name='article_read'),
    path('tags/<slug:tag_slug>/', TagArticleView.as_view(), name='tag_articles'),
    path('like_article/<slug:slug>/', LikeToAuthorView.as_view(), name='article_like'),
    path('delete_comment/<slug:comment_id>/', CommentDeleteView.as_view(), name='comment_delete'),
    path('like_comment/<slug:comment_id>/', CommentLikeView.as_view(), name='comment_like'),
    path('user_articles/<slug:user_id>/', UserArticleView.as_view(), name='user_articles'),
    path('api/', include(router.urls)),
]

authnapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

import authnapp.views as authnapp
from authnapp.apps import AuthnappConfig
from authnapp.views import ProfileView, ProfilePublishedArticlesView, \
    ImageListView, PictureFileCreateView, PictureFileDeleteView, \
    PictureFileUpdateView, MyCommentsListView, ToMeCommentsListView, \
    SearchImageView, ProfileDraftsArticlesView, ProfileDeniedArticlesView, \
    ProfileOnModerationArticlesView, MyMessagesListView, \
    ProfileArticleToModerationView, MessageIsReadView
from .api import HabrUserApi

arouter = DefaultRouter()
arouter.register('habrusers', HabrUserApi)

app_name = AuthnappConfig.name

urlpatterns = [
    path("login/", authnapp.login, name="login"),
    path("logout/", authnapp.logout, name="logout"),
    path("register/", authnapp.register, name="register"),
    path("edit/", authnapp.edit, name="edit"),
    path("password_reset/", authnapp.MyPasswordResetView.as_view(), name='password_reset'),
    path("password_reset_done/", authnapp.MyPasswordResetDone.as_view(), name='password_reset_done'),
    path("reset/<uidb64>/<token>/", authnapp.MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path("password_reset_complete/", authnapp.MyPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('profile/<uuid:pk>/', ProfileView.as_view(), name='profile'),
    path('published_articles/<uuid:pk>/', ProfilePublishedArticlesView.as_view(), name='published_user_articles'),
    path('draft_articles/<uuid:pk>/', ProfileDraftsArticlesView.as_view(), name='draft_user_articles'),
    path('denied_articles/<uuid:pk>/', ProfileDeniedArticlesView.as_view(), name='denied_user_articles'),
    path('on_moderation_articles/<uuid:pk>/', ProfileOnModerationArticlesView.as_view(), name='on_moderation_user_articles'),
    path('article_to_moderation/<slug:article_slug>/', ProfileArticleToModerationView.as_view(),
         name='article_to_moderation'),

    path('api/', include(arouter.urls)),

    path('images/<uuid:pk>/', ImageListView.as_view(), name='user_images'),
    path('load_images/<uuid:pk>/', PictureFileCreateView.as_view(), name='load_images'),
    path('delete_images/<slug:picture_slug>/', PictureFileDeleteView.as_view(),
         name='delete_images'),
    path('update_images/<slug:picture_slug>/', PictureFileUpdateView.as_view(),
         name='update_images'),
    path('search_images/<uuid:pk>/', SearchImageView.as_view(), name='search_images'),

    path('my_comments/<uuid:pk>/', MyCommentsListView.as_view(), name='user_comments'),
    path('to_me_comments/<uuid:pk>/', ToMeCommentsListView.as_view(), name='to_me_comments'),

    path('my_messages/<uuid:pk>/', MyMessagesListView.as_view(), name='user_messages'),
    path('read_message/<slug:slug>/', MessageIsReadView.as_view(), name='read_message'),
]

habr/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework.permissions import AllowAny

from articles.views import MainView, SearchView, page_not_found_view, create_article, help_view, update_article, \
    ArticleCommentRatingView, ArticleLikeRatingView, UserRatingView

schema_view = get_schema_view(
    openapi.Info(
        title="Habr",
        default_version='0.1',
        description="Documentation to out project",
        contact=openapi.Contact(email="admin@admin.local"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=[AllowAny],
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", MainView.as_view(), name="index"),
    path("articles/", include("articles.urls", namespace="articles")),
    path("auth/", include("authnapp.urls", namespace="auth")),
    path('moderation/', include('moderation.urls', namespace='moderation')),
    path("", include("social_django.urls", namespace="social")),
    path('create_article/', create_article, name='create_article'),
    path('update_article/<slug:article_slug>/', update_article, name='update_article'),
    path('search/', SearchView.as_view(), name='search_view'),
    path('search/like/<str:search_string>/', SearchView.as_view(), name='search_view_sort_like'),
    path('search/new/<str:search_string>/', SearchView.as_view(), name='search_view_sort_new'),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('help/', help_view, name='help'),
    path('404/', page_not_found_view,
         kwargs={'exception': Exception('Page not Found')}, name='page_404'),
    path('martor/', include('martor.urls')),
    path("best_articles/", ArticleLikeRatingView.as_view(), name="best_articles"),
    path("discussed_articles/", ArticleCommentRatingView.as_view(), name="discussed_articles"),
    path("users_rating/", UserRatingView.as_view(), name="users_rating"),
]

handler404 = "habr.views.page_not_found_view"

urlpatterns += [re_path('^__debug_/', include(debug_toolbar.urls))]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('404/', page_not_found_view,
                         kwargs={'exception': Exception('Page not Found')}, name='page_404')]

articles/forms.py
from django import forms
from articles.models import Article, Comment
from martor.fields import MartorFormField


class ArticleCreationForm(forms.ModelForm):
    body = MartorFormField()
    def __init__(self, *args, **kwargs):
        super(ArticleCreationForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
    

    class Meta:
        model = Article 
        fields = ('article_category', 'title', 'body', 'tag')


class CommentCreateForm(forms.ModelForm):
    body = MartorFormField()
    def __init__(self, *args, **kwargs):
        super(CommentCreateForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"


    class Meta:
            model = Comment
            fields = ('body', 'parent')

articles/views.py
"""The submodule contains views for working with objects of
articles and categories (sections of the site).
Within this submodule, work is performed with the main entities of the project:
the formation of a set of articles visible to the user or a separate article.

Here are views:

    * to display the main page of the site (to display all articles);
    * to display all articles of the category;
    * to display a separate article;
"""
import logging
from datetime import datetime, timedelta

from bs4 import BeautifulSoup
from django import forms
from django.conf import settings
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.db.models import Count, Q
from django.http import HttpResponseForbidden
from django.shortcuts import HttpResponseRedirect, get_object_or_404, render
from django.urls import reverse
from django.views import View
from django.views.generic import DetailView, ListView, DeleteView
from django.views.generic.edit import FormMixin
from martor.utils import markdownify

from articles.forms import ArticleCreationForm, CommentCreateForm
from articles.models import (Article, Category, Comment, Like, Message,
                             MessageType, Tag)
from authnapp.models import HabrUser

logger = logging.getLogger(__name__)

COMMENTS_BAN = datetime.now() + timedelta(days=14)


def help_view(request):
    return render(request, "articles/help.html")


def page_not_found_view(request, exception):
    """View for the 404 page."""
    context = {}
    context['title'] = '404: Страница не найдена'
    response = render(request, 'articles/misc/404.html', context=context)
    response.status_code = 404
    return response


class MainView(ListView):
    """View for the main page."""
    model = Article
    template_name = 'articles/index.html'
    context_object_name = 'all_articles'
    paginate_by = 5

    def get_queryset(self):
        """Displaying all active articles.
         Articles are displayed in an orderly manner, starting from the most recent."""
        return Article.objects.filter(is_active='ACTIVE'). \
            select_related('user', 'article_category'). \
            only('slug', 'title', 'body', 'create_time',
                 'article_category__slug', 'article_category__category_name',
                 'user__uuid', 'user__username')

    def get_context_data(self, *, object_list=None, **kwargs):
        """Calculates the frequency of occurrence of tags in articles
         and puts in context the 20 most popular tags to display them in the tag cloud."""
        context = super().get_context_data()
        temp_article_queryset = Article.objects.filter(is_active='ACTIVE').values('tag'). \
            annotate(tag_count=Count('tag', distinct=True))
        temp_article_queryset.group_by = ['tag']
        temp_article_queryset = temp_article_queryset.values('tag', 'tag_count'). \
            order_by('-tag_count').values('tag')
        context['cloud_tags'] = Tag.objects.filter(id__in=temp_article_queryset)[:20]
        return context


class CategoryView(ListView):
    """View for articles of a separate category (section)."""
    model = Article
    template_name = 'articles/read_category.html'
    paginate_by = 5
    slug_url_kwarg = 'category_slug'
    category = ''

    def get_queryset(self):
        """Returns a queryset of active articles of the specified category."""
        self.category = Category.objects.get(slug=self.kwargs.get('category_slug'))
        return Article.objects.filter(Q(article_category=self.category), Q(is_active='ACTIVE')). \
            select_related('user', 'article_category').only('slug', 'title', 'body', 'create_time',
                                                            'article_category__slug', 'article_category__category_name',
                                                            'user__uuid', 'user__username')

    def get_context_data(self, *args, **kwargs):
        """Puts the title in the context according to the selected category."""
        context = super().get_context_data(**kwargs)
        context['title'] = f'Посты категории {self.category}'
        return context


class ArticleForm(forms.Form):
    message = forms.CharField()


class ArticleView(FormMixin, DetailView):
    """View for the output of a separate article."""
    model = Article
    template_name = 'articles/read-article.html'
    slug_url_kwarg = 'article_slug'
    form_class = ArticleForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['is_like'] = Like.objects.all().filter(user=self.request.user,
                                                           like_article=self.object.id).count()
        context['is_authenticated'] = self.request.user.is_authenticated
        if context['article'].user.username in self.request.session.keys():
            context['author_is_liked'] = True
        context['is_staff'] = self.request.user.is_staff
        return context

    def get_success_url(self):
        return reverse('author-article_read', kwargs={'slug': self.object.slug})

    def get(self, request, *args, **kwargs):
        """Receives comments and adds context."""
        article = self.object = self.get_object()
        comments = Comment.objects.filter(comment_article=
                                          article.id).select_related('comment_article')
        context = self.get_context_data(**kwargs)
        comment_form = CommentCreateForm()
        context.update({'article': article, 'comments': comments,
                        'comment_form': comment_form})
        return render(request, 'articles/read-article.html', context=context)

    def post(self, request, *args, **kwargs):
        """Creates a comment added by the user, processes the user's call to the comment, adds/removes a like."""
        if 'body' in request.POST:
            self.create_comment(request)
        if 'type' in request.GET:
            self.create_like_or_deny(request)
        return HttpResponseRedirect(request.path)

    def create_comment(self, request):
        """Creates a new comment.
        Initiates a user call if the comment contains usernames of registered
        users in the form of a call."""
        comment_form = CommentCreateForm(request.POST)
        if comment_form.is_valid():
            post = comment_form.save(commit=False)
            post.comment_article = self.get_object()
            post.save()

            users = self.find_nicknames_in_markdown(post.body)
            [self.message_call_create(post, username) for username in users]

    def create_like_or_deny(self, request):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        message_type = request.GET['type']
        if message_type == 'like':
            likes = Like.objects.all().filter(user=request.user, like_article=self.object.id).count()
            if likes == 0:
                Like.objects.create(
                    user=request.user,
                    like_article=self.object
                )
            else:
                like = Like.objects.get(user=request.user, like_article=self.object.id)
                like.delete()
        elif message_type == 'deny':
            self.object.is_active = 'DENY'
            self.object.save()
            try:
                message_sys_type, _ = MessageType.objects.get_or_create(
                    message_type_name='Снятие с публикации', text='Снятие с публикации', sys_type='DENY')
                Message.objects.create(message_type=message_sys_type,
                                       user=self.object.user,
                                       text=f'Ваша статья "{self.object.title}" снята с публикации.')
            except ObjectDoesNotExist:
                pass
            return HttpResponseRedirect(reverse("index"))
        elif message_type == 'delete':
            self.object.is_active = 'USRDEL'
            self.object.save()
            return HttpResponseRedirect(reverse("index"))
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        return super().form_valid(form)

    def find_nicknames_in_markdown(self, markdown_text):
        """Finds the nicknames of users when they are called in the comments."""
        marktext = markdownify(markdown_text)
        soup = BeautifulSoup(marktext, 'html.parser')
        return [username.text[1:] for username in soup.findAll('a', {'class': 'direct-mention-link'})]

    def message_call_create(self, comment, username):
        """Creates a new message for the user when he is called in the comments."""
        try:
            user = HabrUser.objects.get(username=username)
            message_type, _ = MessageType.objects.get_or_create(
                message_type_name='Призыв пользователя', text='Призыв пользователя', sys_type='CALL')
            text = f'Пользователь {comment.user} призывает вас в комментарии к ' \
                   f'статье "{comment.comment_article}"'

            Message.objects.create(
                user=user,
                message_type=message_type,
                text=text,
                related_article=comment.comment_article,
                related_comment=comment
            )
        except ObjectDoesNotExist:
            logger.info('User %s tried to call a non-existent '
                        'user %s in the comments', comment.user, username)


def create_article(request):
    try:
        if request.method == 'POST':
            create_form = ArticleCreationForm(request.POST)
            if create_form.is_valid():
                create_form.save()
                return HttpResponseRedirect(

articles/templates/articles/comment.html
{% load mptt_tags %}
{% load martortags %}


<div class="col-12 text-left">
    <hr>
    {% if article.is_active == 'ACTIVE' %}
        <h2 class="menu-font text-left">
            Комментарии
            <span class="comment_submit_link">{{ comments.count }}</span>
        </h2>
        <br>
        {% if comments %}
            <ul class="no-marker martor-preview">
                {% recursetree comments %}
                    <li>
                        <p><a class="comment-anchor" name="{{ node.slug }}"></a></p>

                        <header class="comment_header">
                            {% if article.user == node.user %}<i class="fa fa-star"></i>{% endif %}
                            <b>{{ node.user }}</b>
                            {{ node.create_time }}<br>
                        </header>

                        {{ node.body | safe_markdown }}

                        <div class="btns">
                            <p class="btns">
                                <a class="comment_submit_link" data-option="{{ node.id }}"
                                   onclick="document.getElementById('comment-submit-button').focus()">
                                    Ответить
                                </a>
                            </p>
                        </div>

                        <div class="inline-buttons">
                            <form class="like-trash-buttons" id="comment_{{ node.id }}_like"
                                  action="{% url 'articles:comment_like' node.id %}" method="POST">
                                {% csrf_token %}
                                <a
                                    {% ifnotequal node.get_likes 0 %}
                                        class="fa fa-heart"
                                    {% else %}
                                        class="fa fa-heart-o"
                                    {% endifnotequal %}
                                        {% if request.user.is_authenticated and not request.user == node.user %}
                                        onclick="document.getElementById('comment_{{ node.id }}_like').submit()"
                                        {% endif %}
                                ></a>
                            </form>
                        </div>
                        <div class="inline-buttons">
                            {{ node.get_likes }}
                        </div>
                        <div class="inline-buttons ml-2">
                            {% if request.user.is_staff or request.user.uuid == node.user.uuid %}
                                <form class="like-trash-buttons" id="comment_{{ node.id }}_delete"
                                      action="{% url 'articles:comment_delete' node.id %}" method="GET">
                                    {% csrf_token %}
                                    <a id="{{ node.id }}"
                                       onclick="document.getElementById('comment_{{ node.id }}_delete').submit()">
                                        <i class="fas fa-trash-alt">
                                        </i>
                                    </a>
                                </form>
                            {% endif %}
                        </div>

                        {% if not node.is_leaf_node %}
                            <ul class="children">
                                {{ children }}
                            </ul>
                        {% endif %}

                    </li>
                {% endrecursetree %}
            </ul>
        {% else %}
            <div class="menu-font text-center">
                Здесь пока нет ни одного комментария, вы можете стать первым!
            </div>
        {% endif %}
    {% endif %}

    <form type="submit" method="post">
        {% csrf_token %}
        {% if request.user.is_authenticated  and article.is_active == 'ACTIVE' %}
            {% if request.user.banned_until == None %}
                <b>Ваш комментарий</b><br><br>
                {{ comment_form.body }}<br>
                <!--
          <div>Родительская статья:
            {{ comment_form.comment_article }}<br>
          </div>
          -->
                <div hidden>Родительский комментарий:
                    {{ comment_form.parent }}<br>
                </div>

                <button id="comment-submit-button" class="col-2 btn btn-dark btn-block">
                    Отправить
                </button>
            {% else %}
                <div class="menu-font text-center">
                    Вы не можете оставлять комментарии по причине бана до: {{ request.user.banned_until }}
                </div>
            {% endif %}
        {% endif %}

    </form>
</div>

articles/templates/articles/index.html
{% extends 'articles/base.html' %}
{% load static %}
{% load martortags %}

{% block title %}Главная страница{% endblock %}

{% block css %}
  <link href="{% static 'plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet" />
  <link href="{% static 'martor/css/martor.bootstrap.min.css' %}" type="text/css" media="all" rel="stylesheet" />
{% endblock %}

{% block content %}

    <!-- Скрипт для облака тегов -->
    <script src="https://www.goat1000.com/jquery.tagcanvas.min.js"></script>
    <script type="text/javascript">
        window.onload = function () {
            try {
                TagCanvas.textColour = '#ffffff';
                TagCanvas.shape = "sphere";
                TagCanvas.textHeight = 30;
                TagCanvas.textColour = '#000000';
                TagCanvas.outlineThickness = 1;
                TagCanvas.outlineColour = "#ffff99";
                TagCanvas.bgOutlineThickness = 0;
                TagCanvas.maxSpeed = 0.03;
                TagCanvas.depth = 0.9;
                TagCanvas.Start('myCanvas');
            } catch (e) {
                document.getElementById('myCanvasContainer').style.display = 'none';
            }
        };
    </script>

    <div id="layoutSidenav_content">
        <main>
             <div class="container-fluid text-center">
                <div class="row card-header">
                    <div class="col-6 text-left">
                        <a href=" {% url 'best_articles' %}">
                            <button class="btn btn-outline-dark btn-block"> Статьи с лучшим рейтингом</button>
                        </a>
                        <a href=" {% url 'discussed_articles' %}">
                            <button class="btn btn-outline-dark btn-block">Самые обсуждаемые статьи</button>
                        </a>
                        <a href=" {% url 'users_rating' %}">
                            <button class="btn btn-outline-dark btn-block">Авторы с лучшим рейтингом</button>
                        </a>
                    </div>
                    <div class="col-6">
                        <div id="myCanvasContainer">
                            <canvas id="myCanvas" width="500vh" height="200vh">
                                <ul>
                                    {% for tag in cloud_tags %}
                                        <li><a href="{% url 'articles:tag_articles' tag.slug %}">{{ tag.tag_name }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </canvas>
                        </div>
                    </div>
                </div>

                <h1 class="mt-4 mb-4">Свежие статьи</h1>

                <!-- Контейнер бесконечной прокрутки, куда подгружаются объекты -->
                <div id="infinite-container" class="infinite-container">
                    {% for article in all_articles %}

                        <div class="infinite-item row main p-3 border border-grey mt-1 mb-1">
                            <div class="col-4">

                                <div class="text-left">
                                    <div class="col-14 row border">
                                        <div class="col-6">
                                            <p>{{ article.create_time | date }}</p>
                                        </div>
                                        <div class="col-3">
                                            <p><i class="fa fa-commenting-o grey"></i><strong>{{ article.get_comments }}</strong></p>
                                        </div>
                                        <div class="col-3">
                                            <p><i class="fa fa-heart-o grey"></i><strong>{{ article.get_likes }}</strong></p>
                                        </div>
                                    </div>
                                    <div class="col-14 row border">
                                        <div class="col-12 text-center">
                                        <a href="{% url 'articles:user_articles' article.user.uuid %}">
                                                <p><strong>{{ article.user }}</strong></p>
                                            </a>
                                        </div>
                                        <div class="col-12 text-center">
                                            <a href="{% url 'articles:category_read' article.article_category.slug %}">
                                                <p><strong>{{ article.article_category }}</strong></p>
                                            </a>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <div class="col-8 mt-3 underlined">
                                <h4>{{ article.title }}</h4>
                            </div>

                            <div class="col-12 mt-5 martor-preview text-left">
                                {{ article.body | safe_markdown | truncatechars_html:350 }}
                            </div>
                            <div class="col-12 text-right">
                                <a class="btn btn-sm btn-outline-dark rounded-3 btn-grey"
                                   href="{% url 'articles:article_read' article.slug %}">Читать статью</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>

                <!-- Вспомогательный объект бесконечной прокрутки, может отображаться при загрузке -->
                <div class="loading" style="display: none;">
                    Загрузка статей...
                </div>

                <!-- Вспомогательный объект бесконечной прокрутки, не отображается на экране -->
                {% if page_obj.has_next %}
                    <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}">More</a>
                {% endif %}

                <!-- Старое меню пагинации -->
                {#                <nav aria-label="Page navigation">#}
                {#                    <ul class="pagination justify-content-center">#}
                {#                        <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">#}
                {#                            <a class="page-link menu-font btn btn-sm btn-outline-dark rounded-3#}
                {#                                            {% if page_obj.has_previous %} btn-grey dark-grey {% else %} btn-grey-disabled {% endif %}"#}
                {#                               href="{% if page_obj.has_previous %} ?page={{ page_obj.previous_page_number }}#}
                {#                                            {% else %} # {% endif %}" tabindex="-1" aria-disabled="true"><i#}
                {#                                    class="fas fa-backward"></i></a>#}
                {#                        </li>#}
                {#                        {% for page in page_obj.paginator.page_range %}#}
                {#                            <li class="page-item">#}
                {#                                <a class="page-link menu-font btn btn-sm btn-outline-dark rounded-3 btn-grey dark-grey"#}
                {#                                   href="?page={{ page }}">{{ page }}</a>#}
                {#                            </li>#}
                {#                        {% endfor %}#}
                {#                        <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">#}
                {#                            <a class="infinite-more-link page-link menu-font btn btn-sm btn-outline-dark rounded-3#}
                {#                                            {% if page_obj.has_next %} btn-grey dark-grey {% else %} btn-grey-disabled {% endif %}"#}
                {#                               href="{% if page_obj.has_next %} ?page={{ page_obj.next_page_number }}#}
                {#                                               {% else %} # {% endif %}"><i class="fas fa-forward"></i></a>#}
                {#                        </li>#}
                {#                    </ul>#}
                {#                </nav>#}

            </div>
        </main>
        {% include 'articles/includes/footer.html' %}
    </div>

    <script>
        let infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            onBeforePageLoad: function () {
                $('.loading').show();
            },
            onAfterPageLoad: function ($items) {
                $('.loading').hide();
            }
        });
    </script>
{% endblock %}