articles/urls.py
from django.urls import path, include
from articles.views import ArticleView, CategoryView, TagArticleView, LikeToAuthorView, UserArticleView, CommentDeleteView, CommentLikeView
from .api import TagApi, ArticleApi, CommentApi, LikeApi, PictureFileApi, MessageApi
from rest_framework.routers import DefaultRouter


router = DefaultRouter()
router.register('tags', TagApi)
router.register('articles', ArticleApi, basename='Article')
router.register('comments', CommentApi)
router.register('likes', LikeApi)
router.register('picturefile', PictureFileApi)
router.register('message', MessageApi)

app_name = 'articles'
urlpatterns = [
    path('categories/<slug:category_slug>/', CategoryView.as_view(), name='category_read'),
    path('<slug:article_slug>/', ArticleView.as_view(), name='article_read'),
    path('tags/<slug:tag_slug>/', TagArticleView.as_view(), name='tag_articles'),
    path('like_article/<slug:slug>/', LikeToAuthorView.as_view(), name='article_like'),
    path('delete_comment/<slug:comment_id>/', CommentDeleteView.as_view(), name='comment_delete'),
    path('like_comment/<slug:comment_id>/', CommentLikeView.as_view(), name='comment_like'),
    path('user_articles/<slug:user_id>/', UserArticleView.as_view(), name='user_articles'),
    path('api/', include(router.urls)),
]

authnapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

import authnapp.views as authnapp
from authnapp.apps import AuthnappConfig
from authnapp.views import ProfileView, ProfilePublishedArticlesView, \
    ImageListView, PictureFileCreateView, PictureFileDeleteView, \
    PictureFileUpdateView, MyCommentsListView, ToMeCommentsListView, \
    SearchImageView, ProfileDraftsArticlesView, ProfileDeniedArticlesView, \
    ProfileOnModerationArticlesView, MyMessagesListView, \
    ProfileArticleToModerationView, MessageIsReadView
from .api import HabrUserApi

arouter = DefaultRouter()
arouter.register('habrusers', HabrUserApi)

app_name = AuthnappConfig.name

urlpatterns = [
    path("login/", authnapp.login, name="login"),
    path("logout/", authnapp.logout, name="logout"),
    path("register/", authnapp.register, name="register"),
    path("edit/", authnapp.edit, name="edit"),
    path("password_reset/", authnapp.MyPasswordResetView.as_view(), name='password_reset'),
    path("password_reset_done/", authnapp.MyPasswordResetDone.as_view(), name='password_reset_done'),
    path("reset/<uidb64>/<token>/", authnapp.MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path("password_reset_complete/", authnapp.MyPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('profile/<uuid:pk>/', ProfileView.as_view(), name='profile'),
    path('published_articles/<uuid:pk>/', ProfilePublishedArticlesView.as_view(), name='published_user_articles'),
    path('draft_articles/<uuid:pk>/', ProfileDraftsArticlesView.as_view(), name='draft_user_articles'),
    path('denied_articles/<uuid:pk>/', ProfileDeniedArticlesView.as_view(), name='denied_user_articles'),
    path('on_moderation_articles/<uuid:pk>/', ProfileOnModerationArticlesView.as_view(), name='on_moderation_user_articles'),
    path('article_to_moderation/<slug:article_slug>/', ProfileArticleToModerationView.as_view(),
         name='article_to_moderation'),

    path('api/', include(arouter.urls)),

    path('images/<uuid:pk>/', ImageListView.as_view(), name='user_images'),
    path('load_images/<uuid:pk>/', PictureFileCreateView.as_view(), name='load_images'),
    path('delete_images/<slug:picture_slug>/', PictureFileDeleteView.as_view(),
         name='delete_images'),
    path('update_images/<slug:picture_slug>/', PictureFileUpdateView.as_view(),
         name='update_images'),
    path('search_images/<uuid:pk>/', SearchImageView.as_view(), name='search_images'),

    path('my_comments/<uuid:pk>/', MyCommentsListView.as_view(), name='user_comments'),
    path('to_me_comments/<uuid:pk>/', ToMeCommentsListView.as_view(), name='to_me_comments'),

    path('my_messages/<uuid:pk>/', MyMessagesListView.as_view(), name='user_messages'),
    path('read_message/<slug:slug>/', MessageIsReadView.as_view(), name='read_message'),
]

habr/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework.permissions import AllowAny

from articles.views import MainView, SearchView, page_not_found_view, create_article, help_view, update_article, \
    ArticleCommentRatingView, ArticleLikeRatingView, UserRatingView

schema_view = get_schema_view(
    openapi.Info(
        title="Habr",
        default_version='0.1',
        description="Documentation to out project",
        contact=openapi.Contact(email="admin@admin.local"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=[AllowAny],
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", MainView.as_view(), name="index"),
    path("articles/", include("articles.urls", namespace="articles")),
    path("auth/", include("authnapp.urls", namespace="auth")),
    path('moderation/', include('moderation.urls', namespace='moderation')),
    path("", include("social_django.urls", namespace="social")),
    path('create_article/', create_article, name='create_article'),
    path('update_article/<slug:article_slug>/', update_article, name='update_article'),
    path('search/', SearchView.as_view(), name='search_view'),
    path('search/like/<str:search_string>/', SearchView.as_view(), name='search_view_sort_like'),
    path('search/new/<str:search_string>/', SearchView.as_view(), name='search_view_sort_new'),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('help/', help_view, name='help'),
    path('404/', page_not_found_view,
         kwargs={'exception': Exception('Page not Found')}, name='page_404'),
    path('martor/', include('martor.urls')),
    path("best_articles/", ArticleLikeRatingView.as_view(), name="best_articles"),
    path("discussed_articles/", ArticleCommentRatingView.as_view(), name="discussed_articles"),
    path("users_rating/", UserRatingView.as_view(), name="users_rating"),
]

handler404 = "habr.views.page_not_found_view"

urlpatterns += [re_path('^__debug_/', include(debug_toolbar.urls))]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('404/', page_not_found_view,
                         kwargs={'exception': Exception('Page not Found')}, name='page_404')]

moderation/urls.py
from django.urls import path

from moderation.views import ModerationPanelView, UserListView,\
    UserDetailView, UserDeleteView, UserGetsBannedView, \
    ArticlesModerListView, ArticleModerDetailView, ArticleRejectedListView, \
    ArticleRejectedDetailView, MessagesListView

app_name = 'moderation'


urlpatterns = [
    path('', ModerationPanelView.as_view(), name='moderation_index'),

    path('users/', UserListView.as_view(), name='moderation_users'),
    path('user-moderation/<uuid:pk>/', UserDetailView.as_view(), name='moderation_user_detail'),
    path('user-delete/<uuid:pk>/', UserDeleteView.as_view(), name='moderation_user_delete'),
    path('user-ban/<uuid:pk>/', UserGetsBannedView.as_view(), name='moderation_user_ban'),

    path('articles/', ArticlesModerListView.as_view(), name='moderation_articles'),
    path('article-moderation/<slug:article_slug>/', ArticleModerDetailView.as_view(),
         name='moderation_article_detail'),
    path('deny-articles/', ArticleRejectedListView.as_view(), name='deny_articles'),
    path('article-recover/<slug:article_slug>/', ArticleRejectedDetailView.as_view(),
         name='recover_article_detail'),

    path('calls/', MessagesListView.as_view(), name='moderation_calls'),
]

authnapp/forms.py
"""
Contains forms for registration and authorization of the user, recovery of his password.
To manage the user's profile, forms are implemented in which he can change some of his data,
as well as change his avatar.
"""

import hashlib
import random

from django import forms
from django.contrib.auth.forms import (AuthenticationForm, UserChangeForm,
                                       UserCreationForm)
from django.core.exceptions import ValidationError
from django.forms import ClearableFileInput, formset_factory, BaseFormSet
from django.utils.translation import gettext_lazy as _

from articles.models import PictureFile
from authnapp.models import HabrUser, HabrUserProfile


class HabrUserLoginForm(AuthenticationForm):
    """A form for authorization of registered users.
    """
    error_messages = {
        'invalid_login': _(
            "Пожалуйста, введите верный логин и пароль с учетом регистра"
        ),
    }

    class Meta:
        """Defines the model involved and the fields used in the form.
        """
        model = HabrUser
        fields = ("username", "password")

    def __init__(self, *args, **kwargs):
        """Manages the classes of form fields for their correct display on the page.
        Sets placeholders for form fields.
        """
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Введите имя пользователя'
        self.fields['password'].widget.attrs['placeholder'] = 'Введите пароль'
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-2 placeholders-text'


class HabrUserRegisterForm(UserCreationForm):
    """A form for registering new users."""

    class Meta:
        """Defines the model involved and the fields used in the form.
         """
        model = HabrUser
        fields = ("username", "first_name", "last_name", "password1", "password2", "email", "age", "avatar")

    def __init__(self, *args, **kwargs):
        """Manages the classes of form fields for their correct display on the page.
        Sets placeholders for form fields.
        """
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Введите имя пользователя'
        self.fields['email'].widget.attrs['placeholder'] = 'Введите адрес эл.почты'
        self.fields['first_name'].widget.attrs['placeholder'] = 'Введите имя'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Введите фамилию'
        self.fields['password1'].widget.attrs['placeholder'] = 'Введите пароль'
        self.fields['password2'].widget.attrs['placeholder'] = 'Подтвердите пароль'
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-2 placeholders-text'

    def clean_age(self):
        data = self.cleaned_data["age"]
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")
        return data

    def save(self):
        user = super(HabrUserRegisterForm, self).save()

        user.is_active = False
        salt = hashlib.sha1(str(random.random()).encode("utf8")).hexdigest()[:6]
        user.activation_key = hashlib.sha1((user.email + salt).encode("utf8")).hexdigest()
        user.save()

        return user


class HabrUserEditForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super(HabrUserEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""

    def clean_age(self):
        data = self.cleaned_data["age"]
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data

    class Meta:
        model = HabrUser
        fields = ("username", "first_name", "email", "age", "avatar")


class HabrUserProfileEditForm(forms.ModelForm):
    class Meta:
        model = HabrUserProfile
        fields = ("tagline", "aboutMe", "gender")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"


class ImageBasePicturesForm(forms.ModelForm):
    """Base form for work with user images."""
    error_messages = {
        'invalid_file_name': _('Отсутствует один или несколько '
                               'заголовков для загружаемых картинок'),
        'too_short_file_name': _('Имя файла должно быть длиннее '
                                 '3 символов - вы ввели %(value)s'),
    }

    class Meta:
        """Defines the model involved and the fields used in the form.
        """
        model = PictureFile
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        """Manages the classes of form fields for their correct display on the page.
        Sets placeholder for 'file_name' form field.
        """
        super().__init__(*args, **kwargs)
        self.fields['file_name'].widget.attrs['placeholder'] = 'Введите заголовок картинки'
        self.fields['file_name'].widget.attrs['class'] = 'form-control'

    def clean(self):
        """Validation of form fields."""
        cleaned_data = super().clean()
        file_name = self.cleaned_data.get('file_name')
        if not file_name:
            msg = ValidationError(self.error_messages['invalid_file_name'],
                                  code='invalid_file_name')
            self.add_error('file_name', msg)

        return cleaned_data

    def clean_file_name(self):
        """Checks if file name isn't shorter than 4 characters."""
        file_name = self.cleaned_data.get('file_name')
        file_name_len = len(file_name)
        if file_name_len <= 3:
            msg = ValidationError(self.error_messages['too_short_file_name'],
                                  code='too_short_file_name',
                                  params={'value': file_name_len})
            self.add_error('file_name', msg)
        return file_name


class ImageLoadPicturesForm(ImageBasePicturesForm):
    """ A form for upload user images."""

    class Meta:
        """Defines the model involved and the fields used in the form.
        Assigns a widget for the 'picture_file' field and a js script attached to it.
        """
        model = PictureFile
        fields = ('file_name', 'picture_file')
        widgets = {'picture_file': ClearableFileInput(
            attrs={"name": "images", "onchange": "readURL(this);",
                   "type": "file", "accept": "image/*"})}

    def __init__(self, *args, **kwargs):
        """Manages the classes of form fields for their correct display on the page.
        """
        super().__init__(*args, **kwargs)
        self.fields['picture_file'].widget.attrs['class'] = 'form-control custom'


class ImageUpdatePicturesForm(ImageBasePicturesForm):
    """ A form for upload user images."""

    class Meta:
        """Defines the model involved and the fields used in the form.
        """
        model = PictureFile
        fields = ('file_name',)


class RequiredFormSet(BaseFormSet):
    """A formset class that forcibly calls validation of all forms included in it.
    Without this class, forms according to Django's provisions are not validated
    for the fullness of fields."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for form in self.forms:
            form.empty_permitted = False


# A formset for uploading images by the user.
ImageFormSet = formset_factory(
    ImageLoadPicturesForm, formset=RequiredFormSet, extra=1
)

authnapp/templates/authnapp/includes/articles_data.html
{% extends 'authnapp/profile/profile.html' %}
{% load static %}


{% block profile-content %}
    <div class="container-fluid text-center menu-font">
        <div class="card mb-4">
            <div class="card-header">
                <div class="row background-light-grey">
                    <div class="col-3">
                        <a class="btn btn-primary btn-grey btn-block m-2"
                           href="{% url 'auth:draft_user_articles' habruserprofile.uuid %}">
                            Черновики
                        </a>
                    </div>
                    <div class="col-3">
                        <a class="btn btn-primary btn-grey btn-block m-2"
                           href="{% url 'auth:on_moderation_user_articles' habruserprofile.uuid %}">
                            На модерации
                        </a>
                    </div>
                    <div class="col-3">
                        <a class="btn btn-primary btn-grey btn-block m-2"
                           href="{% url 'auth:denied_user_articles' habruserprofile.uuid %}">
                            Отклоненные
                        </a>
                    </div>
                    <div class="col-3">
                        <a class="btn btn-primary btn-grey btn-block m-2"
                           href="{% url 'auth:published_user_articles' habruserprofile.uuid %}">
                            Опубликованы
                        </a>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-6">
                        <a class="btn btn-outline-secondary btn-block m-2"
                           href="{% url 'create_article' %}">
                            Создать статью
                        </a>
                    </div>
                </div>
                <div class="row">
                    <div class="table-responsive">
                        <table class="table table-bordered wigth-100 text-center" id="dataTable">
                            <thead class="background-light-grey">
                            <tr>
                                <th>Заголовок</th>
                                <th>Категория</th>
                                <th>Создана</th>
                                <th>Тэги</th>
                                {% if flag == 'ACTIVE' %}
                                    <th>Кол-во лайков</th>
                                {% elif flag == 'DENY' %}
                                    <th>Причина</th>
                                {% elif flag == 'DRAFT' %}
                                    <th>Опубликовать</th>
                                {% endif %}
                            </tr>
                            </thead>
                            <!-- Контейнер бесконечной прокрутки, куда подгружаются объекты -->
                            <tbody class="infinite-container" id="infinite-container">

                            {% for article in user_articles %}
                                <tr class="infinite-item">
                                    <td class="col-3 text-left item-on-page" value="{{ article.id }}">
                                        <a href="{% url 'articles:article_read' article.slug %}"
                                           class="admin-link">{{ article.title }}</a>
                                    </td>
                                    <td class="col-2 text-left">{{ article.article_category }}</td>
                                    <td class="col-2 text-left">{{ article.create_time }}</td>
                                    <td class="col-2 text-left">
                                        {% for tag in article.tag.all %}
                                            <u><a href="{% url 'articles:tag_articles' tag.slug %}">{{ tag }}</a></u>
                                            {% if not forloop.last %},
                                            {% endif %}
                                        {% endfor %}</td>

                                    {% if flag == 'ACTIVE' %}

                                        <td>{{ article.get_likes }}</td>
                                    {% elif flag == 'DENY' %}

                                        <td>
                                            <p>Причины отклонения: {{ article.rejection_reason }}</p>
                                            <form action="{% url 'auth:article_to_moderation' article.slug %}"
                                                  method="post">
                                                {% csrf_token %}
                                                <label for="on_moderation"></label>
                                                <input type="submit" class="btn btn-grey btn-primary btn-block"
                                                       value="На модерацию"
                                                       id="on_moderation">
                                            </form>
                                            <a class="btn btn-grey btn-primary btn-block"
                                               href="{% url 'update_article' article.slug %}">Редактировать</a>
                                        </td>
                                    {% elif flag == 'DRAFT' %}
                                        <td>
                                            <form action="{% url 'auth:article_to_moderation' article.slug %}"
                                                  method="post">
                                                {% csrf_token %}
                                                <label for="on_moderation"></label>
                                                <input type="submit" class="btn btn-grey btn-primary btn-block"
                                                       value="На модерацию"
                                                       id="on_moderation">
                                            </form>
                                            <a class="btn btn-grey btn-primary btn-block"
                                               href="{% url 'update_article' article.slug %}">Редактировать</a>
                                        </td>
                                    {% endif %}
                                </tr>
                            {% empty %}
                                <div class="row main p-3 border border-grey mt-1 mb-1">
                                    <div class="col-12 text-center">
                                        У вас еще нет
                                        {% if flag == 'ACTIVE' %}
                                            опубликованных статей
                                        {% elif flag == 'DENY' %}
                                            статей, отклоненных модератором
                                        {% elif flag == 'DRAFT' %}
                                            черновиков
                                        {% else %}
                                            статей, отправленных на модерацию
                                        {% endif %}
                                    </div>
                                </div>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
            <div class="card-footer">
                <!-- Вспомогательный объект бесконечной прокрутки, может отображаться при загрузке -->
                <div class="loading" style="display: none;">
                    Загрузка статей...
                </div>

                <!-- Вспомогательный объект бесконечной прокрутки, не отображается на экране -->
                {% if page_obj.has_next %}
                    <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}">More</a>
                {% endif %}
                {#                    <nav aria-label="Page navigation">#}
                {#                        <ul class="pagination justify-content-center">#}
                {#                            <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">#}
                {#                                <a class="page-link menu-font btn btn-sm btn-outline-dark rounded-3#}
                {#                            {% if page_obj.has_previous %} btn-grey dark-grey {% else %} btn-grey-disabled {% endif %}"#}
                {#                                   href="{% if page_obj.has_previous %} ?page={{ page_obj.previous_page_number }}#}
                {#                            {% else %} # {% endif %}"#}
                {#                                   tabindex="-1" aria-disabled="true"><i class="fas fa-backward"></i></a>#}
                {#                            </li>#}
                {#                            {% for page in page_obj.paginator.page_range %}#}
                {#                                <li class="page-item">#}
                {#                                    <a class="page-link menu-font btn btn-sm btn-outline-dark rounded-3 btn-grey dark-grey"#}
                {#                                       href="?page={{ page }}">{{ page }}</a>#}
                {#                                </li>#}
                {#                            {% endfor %}#}
                {#                            <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">#}
                {#                                <a class="page-link menu-font btn btn-sm btn-outline-dark rounded-3#}
                {#                            {% if page_obj.has_next %} btn-grey dark-grey {% else %} btn-grey-disabled {% endif %}"#}
                {#                                   href="{% if page_obj.has_next %} ?page={{ page_obj.next_page_number }}#}
                {#                               {% else %} # {% endif %}"><i class="fas fa-forward"></i></a>#}
                {#                            </li>#}
                {#                        </ul>#}
                {#                    </nav>#}
            </div>
        </div>
    </div>

    <script>
        let infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            onBeforePageLoad: function () {
                $('.loading').show();
            },
            onAfterPageLoad: function ($items) {
                $('.loading').hide();
            }
        });
    </script>
{% endblock %}

authnapp/templates/authnapp/includes/inc_user_auth.html
{% if request.user.is_superuser %}
    <a class="dropdown-item" href="/admin">Админка</a>
{% endif %}
{% if request.user.is_staff %}
    <a class="dropdown-item" href="{% url 'moderation:moderation_index' %}">Панель модерации</a>
{% endif %}

{% if request.user.is_authenticated %}
    {#<a class="dropdown-item" href="{% url 'auth:edit' %}">{{ user.username|default:'Пользователь' }}</a>#}
    <a class="dropdown-item" href="{% url 'auth:profile' user.habruserprofile.uuid %}">Личный кабинет: {{ user.username }}</a>
    <a class="dropdown-item" href="{% url 'auth:logout' %}">Выйти из профиля</a>
{% else %}
    <a class="dropdown-item" href="{% url 'auth:login' %}?next={% firstof request.path '/' %}">Войти в профиль</a>
{% endif %}

authnapp/templates/authnapp/includes/my_comments_data.html
{% extends 'authnapp/profile/profile.html' %}
{% load static %}


{% block profile-content %}
    <div class="container-fluid text-center">
    <div class="row mt-2">
        <div class="col-6">
            <a class="btn btn-grey btn-outline-info btn-block"
               href='{% url 'auth:user_comments' habruserprofile.uuid %}'>
                <span class="small-text">Мои комментарии</span></a>
        </div>
        <div class="col-6">
            <a class="btn btn-grey btn-outline-info btn-block"
               href='{% url 'auth:to_me_comments' habruserprofile.uuid %}'>
                <span class="small-text">Комментарии к моему контенту</span></a>
        </div>
    </div>
    <h2 class="mt-4 mb-4">{% block title %}{{ title }}{% endblock %}</h2>

    <!-- Контейнер бесконечной прокрутки, куда подгружаются объекты -->
    <div id="infinite-container" class="infinite-container">
        {% for comment in user_comments %}

            <div class="infinite-item row main p-3 border border-grey mt-1 mb-1">
                <div class="col-4 text-left">
                    <p>Добавлен: {{ comment.create_time | date }}</p>
                    {#                                    <div class="col-12 row border">#}
                    {#                                        <p>Автор: <strong>{{ article.user }}</strong></p>#}
                    {#                                    </div>#}
                </div>
                <div class="col-8 text-right">
                    <p>К статье: <strong><a href="{% url 'articles:article_read' comment.comment_article.slug %}">
                        {{ comment.comment_article }}</a></strong></p>
                </div>
                <div class="col-2 text-left">
                    <p>Лайки: <i class="{% if comment.get_likes == 0 %} fa fa-heart-o {% else %}
                    fas fa fa-heart {% endif %}"></i> {{ comment.get_likes }}</p>
                </div>
                {% if comment.parent %}
                    <div class="col-10 text-right">
                        <p>Ответ на комментарий: <strong>{{ comment.parent }}</strong></p>
                    </div>
                {% endif %}
                <div class="col-12 mt-1 text-left">
                    {{ comment.body | safe | truncatechars:200 }}
                </div>
                {#                            <div class="col-12 text-right">#}
                {#                                <a class="btn btn-sm btn-outline-dark rounded-3 btn-grey"#}
                {#                                   href="{% url 'articles:article_read' article.slug %}">Читать статью</a>#}
                {#                            </div>#}
            </div>

        {% empty %}
            <div class="row main p-3 border border-grey mt-1 mb-1">
                <div class="col-12 text-center">
                    К сожалению, вы еще не написали комментариев
                </div>
            </div>

        {% endfor %}
    </div>

    <!-- Вспомогательный объект бесконечной прокрутки, может отображаться при загрузке -->
    <div class="loading" style="display: none;">
        Загрузка комментариев...
    </div>

    <!-- Вспомогательный объект бесконечной прокрутки, не отображается на экране -->
    {% if page_obj.has_next %}
        <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}">More</a>
    {% endif %}
    </div>
    <script>
        let infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            onBeforePageLoad: function () {
                $('.loading').show();
            },
            onAfterPageLoad: function ($items) {
                $('.loading').hide();
            }
        });
    </script>
{% endblock %}